
name: Python application

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Build package
      run: |
        poetry --version
        poetry build
    - name: Set up config
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
    - name: Publish package
      run: |
        poetry publish  -r https://test.pypi.org/legacy/ -u "__token__" -p ${{ secrets.TEST_PYPI_API_TOKEN }} 